{{- $app := pluck .Values.appname .Values.apps | first }}

{{- range $service := $app.services }}

{{- if $service.ingress }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $service.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/custom-http-errors: "404,502"
    nginx.ingress.kubernetes.io/default-backend: error-pages
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
      - {{ $service.ingress.host }}
  rules:
    - host: {{ $service.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: {{ $service.name }}
              servicePort: 80
{{- end}}

{{- end}}
